// This file is auto-generated by @hey-api/openapi-ts

export type LoginModel = {
    username?: string | null;
    password?: string | null;
};

export type RandomPokemon = {
    name?: string | null;
    type?: string | null;
    image?: string | null;
};

export type RegisterModel = {
    username?: string | null;
    email?: string | null;
    password?: string | null;
};

export type WeatherForecast = {
    date?: string;
    temperatureC?: number;
    summary?: string | null;
    readonly temperatureF?: number;
};

export type PostAuthRegisterData = {
    body?: RegisterModel;
    path?: never;
    query?: never;
    url: '/Auth/register';
};

export type PostAuthRegisterResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostAuthLoginData = {
    body?: LoginModel;
    path?: never;
    query?: never;
    url: '/Auth/login';
};

export type PostAuthLoginResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetRandomPokemonData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/RandomPokemon';
};

export type GetRandomPokemonResponses = {
    /**
     * OK
     */
    200: RandomPokemon;
};

export type GetRandomPokemonResponse = GetRandomPokemonResponses[keyof GetRandomPokemonResponses];

export type GetTestAuthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/TestAuth';
};

export type GetTestAuthResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetWeatherForecastData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/WeatherForecast';
};

export type GetWeatherForecastResponses = {
    /**
     * OK
     */
    200: Array<WeatherForecast>;
};

export type GetWeatherForecastResponse = GetWeatherForecastResponses[keyof GetWeatherForecastResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:7216' | (string & {});
};