# no 'version:' key; compose v2 ignores it and warns
volumes:
  pgdata:
  loki-data:
  grafana-data:

services:
  # Dev container that Cursor/VS Code attaches to
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    depends_on:
      - api
      - web
      - db
      - loki
      - grafana
      - jaeger

  # ASP.NET Core API (runs as your host uid:gid to keep files writable)
  api:
    build:
      context: ..
      dockerfile: MySvelteApp.Server/Dockerfile.dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7216
      - ConnectionStrings__DefaultConnection=Host=db;Database=app;Username=postgres;Password=postgres
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_SERVICE_NAME=my-svelteapp-api
    user: "1000:1000"
    volumes:
      - ../MySvelteApp.Server:/src
    ports:
      - target: 7216
        published: "0"
        protocol: tcp
    depends_on:
      - db
      - jaeger

  # Svelte dev server (also run as your uid:gid)
  web:
    build:
      context: ../MySvelteApp.Client
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=docker-dev
      - PUBLIC_API_ENDPOINT=http://api:7216
      - VITE_API_URL=http://api:7216
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318/v1/traces
      - OTEL_SERVICE_NAME=my-sveltekit-client
    user: "1000:1000"
    volumes:
      - ../MySvelteApp.Client:/app
      - /app/node_modules
    ports:
      - target: 5173
        published: "0"
        protocol: tcp
    depends_on:
      - api
      - jaeger

  # Postgres for local dev
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: "0"
        protocol: tcp
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
      interval: 5s
      timeout: 3s
      retries: 20

  # Loki for app logs (not as docker logging driver)
  loki:
    image: grafana/loki:3.4.1
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml:ro
      - loki-data:/loki
    ports:
      - target: 3100
        published: "0"
        protocol: tcp

  # Grafana
  grafana:
    image: grafana/grafana-oss:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - target: 3000
        published: "0"
        protocol: tcp
    depends_on:
      - loki
      - db
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.57
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - target: 16686
        published: "0"
        protocol: tcp
      - target: 4317
        published: "0"
        protocol: tcp
      - target: 4318
        published: "0"
        protocol: tcp
