// This file is auto-generated by @hey-api/openapi-ts

export type AuthErrorResponse = {
    message?: string | null;
};

export type AuthSuccessResponse = {
    token?: string | null;
    userId?: number;
    username?: string | null;
};

export type LoginModel = {
    username?: string | null;
    password?: string | null;
};

export type RandomPokemon = {
    name?: string | null;
    type?: string | null;
    image?: string | null;
};

export type RegisterModel = {
    username?: string | null;
    email?: string | null;
    password?: string | null;
};

export type WeatherForecast = {
    date?: string;
    temperatureC?: number;
    summary?: string | null;
    readonly temperatureF?: number;
};

export type WeatherForecastWritable = {
    date?: string;
    temperatureC?: number;
    summary?: string | null;
};

export type PostAuthRegisterData = {
    body?: RegisterModel;
    path?: never;
    query?: never;
    url: '/Auth/register';
};

export type PostAuthRegisterErrors = {
    /**
     * Bad Request
     */
    400: AuthErrorResponse;
};

export type PostAuthRegisterError = PostAuthRegisterErrors[keyof PostAuthRegisterErrors];

export type PostAuthRegisterResponses = {
    /**
     * OK
     */
    200: AuthSuccessResponse;
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];

export type PostAuthLoginData = {
    body?: LoginModel;
    path?: never;
    query?: never;
    url: '/Auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Bad Request
     */
    400: AuthErrorResponse;
    /**
     * Unauthorized
     */
    401: AuthErrorResponse;
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * OK
     */
    200: AuthSuccessResponse;
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type GetRandomPokemonData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/RandomPokemon';
};

export type GetRandomPokemonResponses = {
    /**
     * OK
     */
    200: RandomPokemon;
};

export type GetRandomPokemonResponse = GetRandomPokemonResponses[keyof GetRandomPokemonResponses];

export type GetTestAuthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/TestAuth';
};

export type GetTestAuthResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetWeatherForecastData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/WeatherForecast';
};

export type GetWeatherForecastResponses = {
    /**
     * OK
     */
    200: Array<WeatherForecast>;
};

export type GetWeatherForecastResponse = GetWeatherForecastResponses[keyof GetWeatherForecastResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:7216' | (string & {});
};
