// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zAuthErrorResponse = z.object({
    message: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zAuthSuccessResponse = z.object({
    token: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    userId: z.optional(z.int()),
    username: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zLoginModel = z.object({
    username: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    password: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zRandomPokemon = z.object({
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    type: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    image: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zRegisterModel = z.object({
    username: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    email: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    password: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zWeatherForecast = z.object({
    date: z.optional(z.iso.date()),
    temperatureC: z.optional(z.int()),
    summary: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    temperatureF: z.optional(z.int().readonly())
});

export const zWeatherForecastWritable = z.object({
    date: z.optional(z.iso.date()),
    temperatureC: z.optional(z.int()),
    summary: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zPostAuthRegisterData = z.object({
    body: z.optional(zRegisterModel),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPostAuthRegisterResponse = zAuthSuccessResponse;

export const zPostAuthLoginData = z.object({
    body: z.optional(zLoginModel),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPostAuthLoginResponse = zAuthSuccessResponse;

export const zGetRandomPokemonData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetRandomPokemonResponse = zRandomPokemon;

export const zGetTestAuthData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetWeatherForecastData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetWeatherForecastResponse = z.array(zWeatherForecast);
